"use client"

import { useEffect, useRef, useState } from "react"
import { Check, Download, Loader2, X } from "lucide-react"

const NAVY = "#33295e"

export interface ReportAttachment {
  name: string
  url: string
}

interface ReportViewerModalProps {
  report: ReportAttachment
  file: Blob | null
  error: string | null
  isArchived: boolean
  onArchive: () => void
  onClose: () => void
}

export function ReportViewerModal({ report, file, error, isArchived, onArchive, onClose }: ReportViewerModalProps) {
  const bodyRef = useRef<HTMLDivElement>(null)
  const styleRef = useRef<HTMLDivElement>(null)
  const [renderError, setRenderError] = useState<string | null>(null)
  const [isRendered, setIsRendered] = useState(false)

  useEffect(() => {
    if (!file || !bodyRef.current || !styleRef.current) return
    let cancelled = false
    const body = bodyRef.current
    const styles = styleRef.current

    import("docx-preview")
      .then(({ renderAsync }) =>
        renderAsync(file, body, styles, {
          className: "docx",
          inWrapper: true,
          breakPages: true,
          ignoreLastRenderedPageBreak: true,
        }),
      )
      .then(() => {
        if (!cancelled) setIsRendered(true)
      })
      .catch(() => {
        if (!cancelled) setRenderError("This report couldn't be displayed. You can still download it.")
      })

    return () => {
      cancelled = true
      body.innerHTML = ""
      styles.innerHTML = ""
    }
  }, [file])

  useEffect(() => {
    const handleKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose()
    }
    window.addEventListener("keydown", handleKey)
    return () => window.removeEventListener("keydown", handleKey)
  }, [onClose])

  const handleDownload = () => {
    if (!file) return
    const url = URL.createObjectURL(file)
    const link = document.createElement("a")
    link.href = url
    link.download = report.name
    link.click()
    URL.revokeObjectURL(url)
  }

  const message = error ?? renderError
  const isLoading = !message && !isRendered

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" onClick={onClose}>
      <div
        role="dialog"
        aria-modal="true"
        aria-labelledby="report-viewer-title"
        className="flex h-[90vh] w-full max-w-5xl flex-col overflow-hidden rounded-xl bg-white shadow-xl"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between gap-4 border-b border-slate-200 px-6 py-4">
          <div className="flex min-w-0 items-center gap-3">
            <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-md bg-blue-50 text-[10px] font-semibold uppercase text-blue-600">
              docx
            </span>
            <div className="min-w-0">
              <h2 id="report-viewer-title" className="truncate font-semibold text-slate-800">
                {report.name}
              </h2>
              <p className="text-xs text-slate-500">Word document generated by AI Assistant</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="rounded-lg p-2 text-slate-400 transition-colors hover:bg-slate-100 hover:text-slate-600"
            aria-label="Close report viewer"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        <div className="relative flex-1 overflow-auto bg-slate-100">
          <div ref={styleRef} />
          <div ref={bodyRef} className="report-docx-viewer" />
          {isLoading && (
            <div className="absolute inset-0 flex items-center justify-center gap-2 text-sm text-slate-500">
              <Loader2 className="h-4 w-4 animate-spin" />
              Loading report...
            </div>
          )}
          {message && (
            <div className="absolute inset-0 flex items-center justify-center px-6 text-center text-sm text-slate-500">
              {message}
            </div>
          )}
        </div>

        <div className="flex items-center justify-end gap-3 border-t border-slate-200 px-6 py-4">
          <button
            onClick={onClose}
            className="rounded-lg border border-slate-200 px-4 py-2 text-sm font-medium text-slate-700 transition-colors hover:bg-slate-50"
          >
            Close
          </button>
          <button
            onClick={handleDownload}
            disabled={!file}
            className="flex items-center gap-2 rounded-lg border border-slate-200 px-4 py-2 text-sm font-medium text-slate-700 transition-colors hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50"
          >
            <Download className="h-4 w-4" />
            Download
          </button>
          <button
            onClick={onArchive}
            disabled={!file || isArchived}
            className="flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-[#fd6d6d] disabled:cursor-not-allowed disabled:opacity-60 disabled:hover:bg-[#33295e]"
            style={{ backgroundColor: isArchived ? undefined : NAVY }}
          >
            {isArchived && <Check className="h-4 w-4" />}
            {isArchived ? "Saved to Archive" : "Save to Archive"}
          </button>
        </div>
      </div>
    </div>
  )
}
