"use client"

import { useState, useEffect } from "react"
import {
  X,
  CheckCircle2,
  ShieldCheck,
  Calendar,
  Clock,
  User,
  ArrowRightLeft,
  ZoomIn,
  ZoomOut,
  RotateCw,
} from "lucide-react"
import { Button } from "@/components/ui/button"

interface Report {
  id: string
  name: string
  description: string
  category: string
  frequency: string
  lastGenerated?: string
  qnaActive?: boolean
}

interface SignOffRecord {
  reportId: string
  reportName: string
  user: string
  signedAt: string // ISO string
}

interface ReportSignOffModalProps {
  isOpen: boolean
  onClose: () => void
  report: Report | null
  currentUser: string
  existingSignOff?: SignOffRecord | null
  onConfirm: (record: SignOffRecord) => void
}

export function ReportSignOffModal({
  isOpen,
  onClose,
  report,
  currentUser,
  existingSignOff = null,
  onConfirm,
}: ReportSignOffModalProps) {
  const [acknowledged, setAcknowledged] = useState(false)
  const [currentPage, setCurrentPage] = useState(0)
  const [zoom, setZoom] = useState(100)
  // Snapshot the "now" moment when the modal opens so the displayed time is
  // stable and matches what gets recorded on confirm.
  const [now, setNow] = useState<Date>(new Date())

  useEffect(() => {
    if (isOpen) {
      setNow(new Date())
      setAcknowledged(false)
      setCurrentPage(0)
      setZoom(100)
    }
  }, [isOpen])

  const handleZoomIn = () => setZoom((z) => Math.min(z + 25, 200))
  const handleZoomOut = () => setZoom((z) => Math.max(z - 25, 50))

  if (!isOpen || !report) return null

  const isSignedOff = Boolean(existingSignOff)
  const displayDate = existingSignOff ? new Date(existingSignOff.signedAt) : now
  const signatory = existingSignOff?.user ?? currentUser

  const handleConfirm = () => {
    if (!acknowledged || isSignedOff) return
    onConfirm({
      reportId: report.id,
      reportName: report.name,
      user: currentUser,
      signedAt: now.toISOString(),
    })
  }

  // Shared sheet header shown at the top of every page.
  const sheetHeader = (
    <div className="mb-8 flex items-center justify-between border-b-2 border-slate-200 pb-4">
      <div>
        <div className="mb-2 flex h-12 w-12 items-center justify-center rounded-full bg-red-100">
          <div className="flex h-8 w-8 items-center justify-center rounded-full bg-red-500">
            <span className="text-xs font-bold text-white">MAT</span>
          </div>
        </div>
        <h1 className="text-2xl font-bold text-slate-900">{report.name}</h1>
        <p className="text-slate-600">St Clare Catholic Multi Academy Trust</p>
      </div>
      <div className="text-right text-sm text-slate-600">
        <div>Generated: {new Date().toLocaleDateString()}</div>
        <div className="mt-2">
          <span className="rounded-full bg-blue-100 px-3 py-1 text-xs text-blue-800">{report.category}</span>
        </div>
      </div>
    </div>
  )

  const sheetFooter = (pageNumber: number) => (
    <div className="mt-12 border-t border-slate-200 pt-4 text-xs text-slate-500">
      <div className="flex justify-between">
        <span>Confidential Report · {report.frequency}</span>
        <span>
          Page {pageNumber} · Generated by MATpad · {new Date().toLocaleDateString()}
        </span>
      </div>
    </div>
  )

  // Document pages — the preview cycles through these.
  const pages: React.ReactNode[] = [
    // Page 1 — Executive summary
    <>
      {sheetHeader}
      {isSignedOff && (
        <div className="mb-6 flex items-center gap-3 rounded-lg border border-green-200 bg-green-50 p-3">
          <CheckCircle2 className="h-5 w-5 flex-shrink-0 text-green-600" />
          <p className="text-sm text-green-800">
            Signed off by <span className="font-medium">{signatory}</span> on {displayDate.toLocaleDateString()} at{" "}
            {displayDate.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}
          </p>
        </div>
      )}
      <div className="mb-8">
        <h2 className="mb-4 text-xl font-semibold text-slate-900">Executive Summary</h2>
        <p className="mb-4 text-sm leading-relaxed text-slate-700">
          {report.description} This report consolidates the latest available data across the trust to support informed
          decision making and oversight.
        </p>
        <div className="grid grid-cols-2 gap-4">
          <div className="rounded-lg bg-green-50 p-4">
            <h3 className="mb-2 font-medium text-green-900">Overall Performance</h3>
            <div className="text-2xl font-bold text-green-600">Good</div>
          </div>
          <div className="rounded-lg bg-blue-50 p-4">
            <h3 className="mb-2 font-medium text-blue-900">Reporting Period</h3>
            <div className="text-lg font-semibold text-blue-700">Academic Year 2024/25</div>
          </div>
        </div>
      </div>
      {sheetFooter(1)}
    </>,

    // Page 2 — Key performance indicators
    <>
      {sheetHeader}
      <div className="mb-8">
        <h2 className="mb-4 text-xl font-semibold text-slate-900">Key Performance Indicators</h2>
        <div className="grid grid-cols-4 gap-4">
          {[
            { label: "Overall Attendance", value: "94.1%" },
            { label: "Academic Progress", value: "Good" },
            { label: "Behaviour Rating", value: "2" },
            { label: "Staff Retention", value: "92%" },
          ].map((metric) => (
            <div key={metric.label} className="rounded-lg border border-slate-200 p-4 text-center">
              <div className="mb-1 text-xs text-slate-600">{metric.label}</div>
              <div className="text-2xl font-bold text-slate-900">{metric.value}</div>
            </div>
          ))}
        </div>
      </div>
      <div className="mb-8">
        <h2 className="mb-4 text-xl font-semibold text-slate-900">Attendance by Academy</h2>
        <div className="overflow-hidden rounded-lg border border-slate-200">
          <table className="w-full text-sm">
            <thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500">
              <tr>
                <th className="px-4 py-2">Academy</th>
                <th className="px-4 py-2">Attendance</th>
                <th className="px-4 py-2">Persistent Absence</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {[
                { name: "St Clare Primary", att: "95.2%", pa: "8.1%" },
                { name: "St Augustine's", att: "93.8%", pa: "11.4%" },
                { name: "Holy Cross", att: "94.6%", pa: "9.7%" },
                { name: "St Thomas More", att: "92.9%", pa: "12.2%" },
              ].map((row) => (
                <tr key={row.name}>
                  <td className="px-4 py-2 font-medium text-slate-900">{row.name}</td>
                  <td className="px-4 py-2 text-slate-700">{row.att}</td>
                  <td className="px-4 py-2 text-slate-700">{row.pa}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
      {sheetFooter(2)}
    </>,

    // Page 3 — Narrative & recommendations
    <>
      {sheetHeader}
      <div className="mb-8">
        <h2 className="mb-4 text-xl font-semibold text-slate-900">Commentary &amp; Recommendations</h2>
        <p className="mb-4 text-sm leading-relaxed text-slate-700">
          Performance across the trust remains strong, with attendance and staff retention holding above target.
          Continued focus is recommended on reducing persistent absence at the secondary phase and sustaining the
          positive trajectory in academic progress.
        </p>
        <ul className="mb-4 list-disc space-y-2 pl-5 text-sm text-slate-700">
          <li>Maintain targeted attendance interventions in the two academies below 94%.</li>
          <li>Embed the revised behaviour policy across all phases by the next reporting window.</li>
          <li>Review staffing structures ahead of the summer recruitment cycle.</li>
        </ul>
      </div>
      {sheetFooter(3)}
    </>,
  ]

  const totalPages = pages.length

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4">
      <div className="flex h-full max-h-[90vh] w-full max-w-5xl flex-col overflow-hidden rounded-lg border border-slate-200 bg-white shadow-xl">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-200 p-4">
          <div>
            <h2 className="text-lg font-semibold text-slate-900">Sign off report</h2>
            <p className="text-sm text-slate-600">{report.name}</p>
          </div>
          <Button variant="ghost" size="sm" onClick={onClose} aria-label="Close">
            <X className="h-5 w-5" />
          </Button>
        </div>

        {/* Body */}
        <div className="flex flex-1 flex-col overflow-hidden lg:flex-row">
          {/* PDF preview */}
          <div className="flex min-w-0 flex-1 flex-col bg-slate-100">
            {/* Viewer toolbar */}
            <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 bg-slate-50 p-3">
              <div className="flex flex-wrap items-center gap-3">
                {/* Page navigation */}
                <div className="flex items-center gap-2">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => setCurrentPage((p) => Math.max(0, p - 1))}
                    disabled={currentPage === 0}
                  >
                    Previous
                  </Button>
                  <span className="text-sm text-slate-600">
                    Page {currentPage + 1} of {totalPages}
                  </span>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => setCurrentPage((p) => Math.min(totalPages - 1, p + 1))}
                    disabled={currentPage === totalPages - 1}
                  >
                    Next
                  </Button>
                </div>

                {/* Zoom controls */}
                <div className="flex items-center gap-2 border-l border-slate-300 pl-3">
                  <Button variant="outline" size="sm" onClick={handleZoomOut} disabled={zoom <= 50}>
                    <ZoomOut className="h-4 w-4" />
                  </Button>
                  <span className="min-w-[52px] text-center text-sm text-slate-600">{zoom}%</span>
                  <Button variant="outline" size="sm" onClick={handleZoomIn} disabled={zoom >= 200}>
                    <ZoomIn className="h-4 w-4" />
                  </Button>
                </div>

                {/* Reset */}
                <div className="flex items-center gap-2 border-l border-slate-300 pl-3">
                  <Button variant="outline" size="sm" onClick={() => setZoom(100)} aria-label="Reset zoom">
                    <RotateCw className="h-4 w-4" />
                  </Button>
                </div>
              </div>

              {/* Fit options */}
              <div className="flex items-center gap-2">
                <Button variant={zoom === 100 ? "default" : "outline"} size="sm" onClick={() => setZoom(100)}>
                  Fit Width
                </Button>
                <Button variant={zoom === 75 ? "default" : "outline"} size="sm" onClick={() => setZoom(75)}>
                  Fit Page
                </Button>
              </div>
            </div>

            {/* Document */}
            <div className="flex-1 overflow-auto p-4">
              <div className="flex justify-center">
                <div
                  className="bg-white shadow-lg"
                  style={{
                    transform: `scale(${zoom / 100})`,
                    transformOrigin: "top center",
                    width: "210mm",
                  }}
                >
                  <div className="p-8">{pages[currentPage]}</div>
                </div>
              </div>
            </div>
          </div>

          {/* Sign-off panel */}
          <div className="w-full flex-shrink-0 overflow-auto border-t border-slate-200 bg-white p-6 lg:w-80 lg:border-l lg:border-t-0">
            <h3 className="mb-1 text-base font-semibold text-slate-900">Confirm sign off</h3>
            <p className="mb-6 text-sm text-slate-600">
              Review the report on the left, then confirm your sign off. This will be recorded against your name.
            </p>

            {/* Details */}
            <div className="space-y-4">
              <div className="flex items-start gap-3">
                <User className="mt-0.5 h-4 w-4 flex-shrink-0 text-slate-400" />
                <div>
                  <div className="text-xs uppercase tracking-wide text-slate-500">Signed off by</div>
                  <div className="text-sm font-medium text-slate-900">{signatory}</div>
                </div>
              </div>
              <div className="flex items-start gap-3">
                <Calendar className="mt-0.5 h-4 w-4 flex-shrink-0 text-slate-400" />
                <div>
                  <div className="text-xs uppercase tracking-wide text-slate-500">Date</div>
                  <div className="text-sm font-medium text-slate-900">
                    {displayDate.toLocaleDateString(undefined, {
                      weekday: "long",
                      year: "numeric",
                      month: "long",
                      day: "numeric",
                    })}
                  </div>
                </div>
              </div>
              <div className="flex items-start gap-3">
                <Clock className="mt-0.5 h-4 w-4 flex-shrink-0 text-slate-400" />
                <div>
                  <div className="text-xs uppercase tracking-wide text-slate-500">Time</div>
                  <div className="text-sm font-medium text-slate-900">
                    {displayDate.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" })}
                  </div>
                </div>
              </div>
            </div>

            {/* Data migration notice — informational only */}
            <div className="mt-6 rounded-lg border border-[#fd6d6d]/30 bg-[#fd6d6d]/10 p-4">
              <div className="mb-2 flex items-center gap-2">
                <ArrowRightLeft className="h-4 w-4 flex-shrink-0 text-[#fd6d6d]" />
                <h4 className="text-sm font-semibold text-slate-900">Data moves on sign off</h4>
              </div>
              <p className="mb-3 text-xs leading-relaxed text-slate-600">
                Signing off closes the current data window and moves the data embedded in this report into the next
                window. The following will be carried forward:
              </p>
              <ul className="space-y-1.5 text-xs text-slate-700">
                <li className="flex items-center gap-2">
                  <span className="h-1.5 w-1.5 flex-shrink-0 rounded-full bg-[#fd6d6d]" />
                  Form data
                </li>
                <li className="flex items-center gap-2">
                  <span className="h-1.5 w-1.5 flex-shrink-0 rounded-full bg-[#fd6d6d]" />
                  Report data
                </li>
              </ul>
              <p className="mt-3 text-xs leading-relaxed text-slate-600">
                Once signed off, the current window becomes read-only.
              </p>
            </div>

            {isSignedOff ? (
              <div className="mt-6 flex items-center gap-2 rounded-lg border border-green-200 bg-green-50 p-3">
                <CheckCircle2 className="h-5 w-5 flex-shrink-0 text-green-600" />
                <span className="text-sm font-medium text-green-800">This report has been signed off.</span>
              </div>
            ) : (
              <>
                <label className="mt-6 flex cursor-pointer items-start gap-3 rounded-lg border border-slate-200 p-3 hover:bg-slate-50">
                  <input
                    type="checkbox"
                    checked={acknowledged}
                    onChange={(e) => setAcknowledged(e.target.checked)}
                    className="mt-0.5 h-4 w-4 rounded border-slate-300 text-primary focus:ring-primary"
                  />
                  <span className="text-sm text-slate-700">
                    I confirm I have reviewed this report and approve it for sign off.
                  </span>
                </label>

                <Button
                  onClick={handleConfirm}
                  disabled={!acknowledged}
                  className="mt-4 w-full bg-primary text-primary-foreground hover:bg-primary/90 disabled:opacity-50"
                >
                  <ShieldCheck className="mr-2 h-4 w-4" />
                  Confirm sign off
                </Button>
              </>
            )}

            <Button variant="outline" onClick={onClose} className="mt-2 w-full bg-transparent">
              {isSignedOff ? "Close" : "Cancel"}
            </Button>
          </div>
        </div>
      </div>
    </div>
  )
}
